{% set version = "0.3.25" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-adehabitatlt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adehabitatLT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adehabitatLT/adehabitatLT_{{ version }}.tar.gz
  sha256: 97489532e3d8fdec912471700ec1811db517a7478bc243a20b01beac128f03ed

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-circstats
    - r-ade4
    - r-adehabitatma
    - r-sp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-circstats
    - r-ade4
    - r-adehabitatma
    - r-sp

test:
  commands:
    - $R -e "library('adehabitatLT')"           # [not win]
    - "\"%R%\" -e \"library('adehabitatLT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=adehabitatLT
  license: GPL-2.0-or-later
  summary: A collection of tools for the analysis of animal movements.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: adehabitatLT
# Version: 0.3.24
# Date: 2019-04-07
# Depends: R (>= 2.10.0), sp, methods, ade4, adehabitatMA, CircStats, stats
# Suggests: maptools, tkrplot, MASS
# Imports: graphics, grDevices, utils
# Title: Analysis of Animal Movements
# Author: Clement Calenge, contributions from Stephane Dray and Manuela Royer
# Maintainer: Clement Calenge <clement.calenge@oncfs.gouv.fr>
# Description: A collection of tools for the analysis of animal movements.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-04-07 15:55:30 UTC; calenge
# Repository: CRAN
# Date/Publication: 2019-04-07 16:52:54 UTC
