# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OZOUi/enL2h1y6I3VtbCe2C34GdsUhvFDnJ8vXC4KbOo92YI12FjYQoMBYjfDOkKG02li4nTmSeEAh8a0rAxwqX1fljQ2hzKYxg4X6pRtu77C+FBZydkxtGH5sVKJ7Vn4cR0ATU3FoP2iYRoKg7qNgeDrS5ishPkP8jUnspxpv5lZ84nBoOJI0aTvMh4Sodg4XdpOhcnFI9xKlWi7j8/6JcKdH0k6ScfKAibIxIZBT1D/2E+4OGp9BY1eurcAiJKAmEnjG3MDgVO0Ei45PVwcf1US2jDDA0thfxz8IcPo5ENb/+6Yn78ZR3IGjIy0GWdnm+IfUdu4BXdMrbzFkpYCU3OB3vdXadptxk8guPt2HS48WAzAxniPT8TfxtgFPhVy/wyx/Gn4WrJ/xV8j2fnPl5QiEtCFWyMPPok5psKRkRCLQIJZ1zYayLV9PVbuUmdgG2IwNjpXKP2lLJyiCj2baGxc97tvfRZjyanGj7yBGr+5KLgigX+E9E5fq+o03nMzJjViuCJlYbJrkaxoz4j6c2wmzvsK1ct/iIFNxiQMdaY7J/MLAEDLrd0xg14uAYtI8uaCiamzf0yjlm3UoJdP0/nD8chz7to3CCWAZSdn49xAI5yOvjS73ScUSwNBZcrf/nxJGDt5NwUFGYr6QMk/M+e73qhgrJwJLo+QXXWAns="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml