appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OZOUi/enL2h1y6I3VtbCe2C34GdsUhvFDnJ8vXC4KbOo92YI12FjYQoMBYjfDOkKG02li4nTmSeEAh8a0rAxwqX1fljQ2hzKYxg4X6pRtu77C+FBZydkxtGH5sVKJ7Vn4cR0ATU3FoP2iYRoKg7qNgeDrS5ishPkP8jUnspxpv5lZ84nBoOJI0aTvMh4Sodg4XdpOhcnFI9xKlWi7j8/6JcKdH0k6ScfKAibIxIZBT1D/2E+4OGp9BY1eurcAiJKAmEnjG3MDgVO0Ei45PVwcf1US2jDDA0thfxz8IcPo5ENb/+6Yn78ZR3IGjIy0GWdnm+IfUdu4BXdMrbzFkpYCU3OB3vdXadptxk8guPt2HS48WAzAxniPT8TfxtgFPhVy/wyx/Gn4WrJ/xV8j2fnPl5QiEtCFWyMPPok5psKRkRCLQIJZ1zYayLV9PVbuUmdgG2IwNjpXKP2lLJyiCj2baGxc97tvfRZjyanGj7yBGr+5KLgigX+E9E5fq+o03nMzJjViuCJlYbJrkaxoz4j6c2wmzvsK1ct/iIFNxiQMdaY7J/MLAEDLrd0xg14uAYtI8uaCiamzf0yjlm3UoJdP0/nD8chz7to3CCWAZSdn49xAI5yOvjS73ScUSwNBZcrf/nxJGDt5NwUFGYr6QMk/M+e73qhgrJwJLo+QXXWAns=}
